spring:

#CICD 배포시에 추가 설정 필요!
  datasource:
    url: jdbc:mysql://studyground-db.cdqu1tqs7wnb.ap-northeast-2.rds.amazonaws.com:3306/newstudyground
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none #none으로 변경
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true